### ISSUE TITLE
Archiving the repo

### ISSUE THREAD

**Issue by kiriappeee** [bufferapp/buffer-icons#34]
Heyya @hamstu . Just wanted to give a heads up that I'll be archiving this repo this week as part of the cleanup process of the cibot jenkins instance and all related resources. The scheduled date for archival of this repo and the deletion of the [associated cibot job](https://cibot.bufferapp.com/job/buffer-icons/) is 15th July (this Thursday) 

My assumption is that this shouldn't cause any issues but just wanted to give a heads up before proceeding. Let me know if there's anything I shouldn't go ahead with or anything I should preserve in the cleanup process. Thanks 🙌

**Comment by hamstu** [comment]
@kiriappeee This should be fine @kiriappeee – there are likely still a few places where we're using these icons. But they reference the location on S3 I think, so removing this repo shouldn't have any effect, and I see no reason why we should keep the legacy icons around. 

Thanks for the heads up! 👍🏻
